import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const base = process.env.LIFE_CLOCK_URL || 'http://127.0.0.1:4178';
const context = await chromium.launchPersistentContext('', { headless: true, ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}), viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
const browser = context.browser();
const page = await context.newPage(), errors = [], requests = [], results = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => requests.push({ url: request.url(), method: request.method(), data: request.postData() }));
const record = name => { results.push(name); console.log('PASS', name); };
const artifacts = new URL('./artifacts/', import.meta.url); await mkdir(artifacts, { recursive: true });
try {
  await page.goto(`${base}/life-clock/`);
  await page.locator('#welcome').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#setup').isVisible(), false); record('First visit CTA without input overload');
  await page.locator('#start').click();
  assert.equal(await page.locator('#profile-form input').count(), 6);
  await page.locator('[name=age]').fill('36'); await page.locator('#profile-form button[type=submit]').click();
  await page.locator('#dashboard').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#healthy-days').textContent(), '14,245');
  assert.match(await page.locator('#asset-lifetime').textContent(), /^66\./); record('Case A form to calculated dashboard');
  await page.evaluate(await readFile(createRequire(import.meta.url).resolve('axe-core/axe.min.js'), 'utf8'));
  const accessibility = await page.evaluate(async () => (await axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } })).violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => n.target) })));
  assert.deepEqual(accessibility, []); record('Automated WCAG A/AA accessibility audit');
  await page.locator('details').filter({ hasText: '自分だけの' }).locator('summary').click();
  await page.locator('#event-form [name=name]').fill('<img src=x onerror=alert(1)>'); await page.locator('#event-form button').click();
  assert.equal(await page.locator('.event-card').count(), 6); assert.equal(await page.locator('.event-card img').count(), 0); record('Custom event saved with safe text rendering');
  await page.locator('#log-text').fill('子どもと公園。帰りにアイス。'); await page.locator('#log-form button').click();
  assert.equal(await page.locator('#memory-count').textContent(), '1'); record('Life log and memory counter');
  await page.evaluate(() => { window.testShare = null; Object.defineProperty(navigator, 'share', { configurable: true, value: async data => { window.testShare = data; } }); });
  await page.locator('#share').click(); const share = await page.evaluate(() => window.testShare);
  assert.match(share.text, /残りの夏：39回/); assert.ok(!share.text.includes('6000') && !share.text.includes('公園') && !share.text.includes('36歳')); record('Share contains only seasons and public URL');
  await page.reload(); await page.locator('#dashboard').waitFor({ state: 'visible' });
  assert.equal(await page.locator('.event-card').count(), 6); assert.equal(await page.locator('#memory-count').textContent(), '1'); record('Reload restores dashboard, events and logs');
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload();
  assert.equal(await page.evaluate(() => Boolean(navigator.serviceWorker.controller)), true);
  const manifest = await (await context.request.get(`${base}/life-clock/manifest.webmanifest`)).json();
  assert.equal(manifest.display, 'standalone'); assert.equal(manifest.scope, '/life-clock/');
  for (const icon of manifest.icons) assert.equal((await context.request.get(base + icon.src)).status(), 200);
  const cdp = await context.newCDPSession(page); await cdp.send('Page.enable');
  const installability = await cdp.send('Page.getInstallabilityErrors'); assert.deepEqual(installability.installabilityErrors, []);
  record('Manifest, dedicated scope, all icons and Chromium installability');
  await context.setOffline(true); await page.reload(); await page.locator('#dashboard').waitFor({ state: 'visible' });
  await page.locator('#log-text').fill('オフラインで読書'); await page.locator('#log-form button').click();
  assert.equal(await page.locator('#memory-count').textContent(), '2'); record('Offline reload and log save');
  await context.setOffline(false);
  for (const width of [320, 390, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 }); await page.waitForTimeout(200);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `overflow at ${width}`);
    const box = await page.locator('#chart svg').boundingBox(); assert.ok(box.width <= width && box.width > 100); record(`Responsive chart and no horizontal overflow at ${width}px`);
  }
  await page.setViewportSize({ width: 1280, height: 900 }); await page.screenshot({ path: (await import('node:url')).fileURLToPath(new URL('desktop-dashboard.png', artifacts)), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: (await import('node:url')).fileURLToPath(new URL('mobile-dashboard.png', artifacts)), fullPage: true });
  await page.locator('#edit-profile').click();
  await page.locator('[name=spending]').fill('0'); await page.locator('#profile-form button[type=submit]').click();
  assert.ok(await page.locator('#error-spending').textContent()); record('Zero expenses validation');
  await page.locator('[name=spending]').fill('300'); await page.locator('[name=healthspan]').fill('35'); await page.locator('#profile-form button[type=submit]').click();
  assert.ok(await page.locator('#error-healthspan').textContent()); record('Healthspan below age validation');
  await page.locator('[name=healthspan]').fill('90'); await page.locator('#profile-form button[type=submit]').click();
  assert.ok(await page.locator('#error-healthspan').textContent()); record('Healthspan beyond lifespan validation');
  await page.locator('[name=healthspan]').fill('36'); await page.locator('[name=assets]').fill('0'); await page.locator('#profile-form button[type=submit]').click();
  assert.equal(await page.locator('#healthy-days').textContent(), '0'); assert.equal(await page.locator('#daily-budget').textContent(), '—'); assert.match(await page.locator('#final-assets').textContent(), /^0/); record('Zero assets and health horizon do not crash');
  await page.evaluate(() => { const key = 'wakuwaku.life-clock.v1', p = JSON.parse(localStorage.getItem(key)); p.lastVisit = new Date(Date.now() - 7 * 86400000).toISOString(); localStorage.setItem(key, JSON.stringify(p)); localStorage.setItem('other-app', 'preserved'); });
  await page.reload(); assert.match(await page.locator('#return-message').textContent(), /前回から7日/); record('Seven-day revisit message');
  await page.locator('[data-nav=settings]').click();
  page.once('dialog', dialog => dialog.dismiss()); await page.locator('#reset').click();
  assert.ok(await page.evaluate(() => localStorage.getItem('wakuwaku.life-clock.v1'))); record('Reset cancellation preserves data');
  page.once('dialog', dialog => dialog.accept()); await page.locator('#reset').click();
  await page.locator('#welcome').waitFor({ state: 'visible' });
  assert.equal(await page.evaluate(() => localStorage.getItem('wakuwaku.life-clock.v1')), null);
  assert.equal(await page.evaluate(() => localStorage.getItem('other-app')), 'preserved'); record('Confirmed reset deletes only life clock data');
  assert.deepEqual(errors, []); assert.equal(requests.filter(r => !r.url.startsWith(base)).length, 0); assert.equal(requests.filter(r => r.method !== 'GET').length, 0); record('No console exceptions, external requests or personal data transmission');
  const broken = await browser.newContext(); await broken.addInitScript(() => localStorage.setItem('wakuwaku.life-clock.v1', '{bad'));
  const bp = await broken.newPage(); await bp.goto(`${base}/life-clock/`); await bp.locator('#settings').waitFor({ state: 'visible' });
  assert.equal(await bp.evaluate(() => localStorage.getItem('wakuwaku.life-clock.v1')), '{bad'); record('Corrupt storage preserved with recovery UI'); await broken.close();
  const quota = await browser.newContext(); await quota.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError'); }; });
  const qp = await quota.newPage(); await qp.goto(`${base}/life-clock/`); await qp.locator('#start').click(); await qp.locator('[name=age]').fill('36'); await qp.locator('#profile-form button[type=submit]').click(); assert.match(await qp.locator('#notice').textContent(), /保存できません/); assert.equal(await qp.locator('#dashboard').isVisible(), false); record('Storage failure never claims saved success'); await quota.close();
  await writeFile(new URL('browser-results.json', artifacts), JSON.stringify({ passed: results.length, results, errors, installability, requests: requests.length }, null, 2));
} finally { await browser.close(); }
